### PR TITLE
Database Connection and Other for Vertical Flatten

### LINKED ISSUE #20: DB For Vertical Flattening
DB For Vertical Flattening

### PR DESCRIPTION
**Pull request by psharma1998**
Database Connection and Other for Vertical Flatten
1. New Fun in Vertical Flatten to connect to DB
2. Wrapper Class in new File for VF Database
3. Replace . with _ as it gives error while Creating Table

### CODE REVIEW

**Comment by psharma1998** [comment]
Tested all 4 Cases from .txt file, and verified DB is created successfully or not

**Review by ns-psingh — APPROVED** [review]
LGTM! Let @Ritik19 also approve

**Comment by ns-psingh** [comment]
@Ritik19 if we're planning to keep vertical db and horizontal db modules seperate, we shall rename the database module to database_horizontal

**Comment by Ritik19** [comment]
For the time being, parth has kept it separate, we can combine it as 1 db
module. But if time is short, no harm in going with separate modules
either, we can rename the earlier db module then.

**Comment by psharma1998** [comment]
If we want to create a common file then we can do it in next PR. For now if it's good, @ritik can merge it.

**Review by Ritik19 — APPROVED** [review]

**Pull request merged**
